version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs/dev/nginx:/var/log/nginx
      - ./docker/nginx/files/dockerhost/file/:/etc/docker-host/
      - ./docker/nginx/files/nginx.conf/file/:/etc/nginx.conf/
    restart: always

  nginx-web-interface-dev:
    container_name: nginx-web-interface-dev
    build:
      context: .
      dockerfile: ./docker/web/dev/Dockerfile
    env_file:
      - ./docker/web/dev/web.env
    ports:
      - '3099:3099'
    volumes:
      - ./app:/app
      - ./docker/nginx/files/nginx.conf/file/:/etc/nginx.conf/
    restart: always
